#!/bin/bash

argocd_latest_version=$(
  curl \
    --silent \
    --url "https://api.github.com/repos/argoproj/argo-cd/releases/latest" \
  | grep '"tag_name"' \
  | sed -E 's/.*"([^"]+)".*/\1/'
)

sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${argocd_latest_version}/argocd-linux-amd64

sudo chmod +x /usr/local/bin/argocd
