#!/bin/bash
commit_msg_file="${1}"

# Check if the commit message matches the conventional commit pattern
if ! grep -qE "^(bump|build|feat|fix|docs|style|refactor|perf|test|chore|ci|revert)(\([^)]+\))?(\!)?\: .{1,}$" "${commit_msg_file}"; then
  cat <<EOF

  Error:
  
    Commit message does not follow Conventional Commits format!


  Please use the Conventional Commits format: 
  
    <type>(<scope>): <description>


  Examples:

    feat(api): add new feature

    fix: fix a bug

    docs: update documentation

    feat!: breaking change


  Your commit message:

    $(cat ${commit_msg_file})

EOF
  exit 1
fi
