#!/bin/bash
if [[ -f ~/trash/token ]]; then
  token="$(cat ~/trash/token)"
else
  token="Bearer 123"
fi

generated_uuid="$(uuidgen)"

curl \
  --include \
  --request POST \
  --url https://httpbin.org/post \
  --header "Content-Type: application/json" \
  --header "Authorization: ${token?}" \
  --data @- << EOF
{
  "id": "${generated_uuid?}",
  "name": "A regular data"
}
EOF

cat << EOF > /tmp/httpbin.json
{
  "id": "${generated_uuid?}",
  "name": "A regular data"
}
EOF

curl \
  --include \
  --request POST \
  --url https://httpbin.org/post \
  --header "Content-Type: application/json" \
  --header "Authorization: ${token?}" \
  --data @/tmp/httpbin.json
