#!/bin/bash
if [[ -f ~/trash/token ]]; then
  TOKEN="$(cat ~/trash/token)"
else
  TOKEN="Bearer 123"
fi

GENERATED_UUID="$(uuidgen)"

curl \
  --include \
  --request POST \
  --url https://httpbin.org/post \
  --header "Content-Type: application/json" \
  --header "Authorization: ${TOKEN?}" \
  --data @- << EOF
{
  "id": "${GENERATED_UUID?}",
  "name": "A regular data"
}
EOF

cat << EOF > /tmp/httpbin.json
{
  "id": "${GENERATED_UUID?}",
  "name": "A regular data"
}
EOF

curl \
  --include \
  --request POST \
  --url https://httpbin.org/post \
  --header "Content-Type: application/json" \
  --header "Authorization: ${TOKEN?}" \
  --data @/tmp/httpbin.json
