#!/bin/bash
this_script_path="$(realpath ${0})"
this_script_name="${this_script_path##*/}"

api_version="2021-10-01"
granularity="None"

show_usage() {
  cat <<EOF

  Azure Costs

    Options:

      -h, --help                      Show this help
      -s, --subscription              Subscription ID
      -sd, --start-date               Start date
      -ed, --end-date                 End date
     

    Examples:

      ${this_script_name} \\
        --help

      ${this_script_name} \\
        --subscription \${ARM_SUBSCRIPTION_ID} \\
        --start-date "2021-10-01" \\
        --end-date "2021-10-31"

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
  case $1 in
    -h | --help )
      show_usage
      exit 1
      ;;

    -s | --subscription )
      shift
      subscription_id="${1}"
      ;;

    -sd | --start-date )
      shift
      start_date="${1}"
      ;;
    
    -ed | --end-date )
      shift
      end_date="${1}"
      ;;

  esac
  shift
done

if [[ "$1" == '--' ]]; then shift; fi

if [[ -z "${subscription_id}" ]]; then
  echo "Error: Subscription ID is required: -s | --subscrition"
  show_usage
  exit 1
fi

# If start date is not provided, set it to the first day of the last month
if [[ -z "${start_date}" ]]; then
  start_date=$(date -d "$(date +%Y-%m-01) -1 month" +%Y-%m-01)
fi

# If end date is not provided, set it to the last day of the last month
if [[ -z "${end_date}" ]]; then
  end_date=$(date -d "$(date +%Y-%m-01) -1 day" +%Y-%m-%d)
fi

# Retrieve access token
access_token=$(az account get-access-token \
  --query accessToken \
  --output tsv)

# API URL
cost_management_url="https://management.azure.com/subscriptions/${subscription_id}/providers/Microsoft.CostManagement/query?api-version=${api_version}"

# Payload request
read -r -d '' payload << EOF
{
  "type": "ActualCost",
  "timeframe": "Custom",
  "timePeriod": {
    "from": "${start_date}",
    "to": "${end_date}"
  },
  "dataset": {
    "granularity": "${granularity}",
    "aggregation": {
      "totalCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      },
      "totalCostUSD": {
        "name": "CostUSD",
        "function": "Sum"
      }
    },
    "grouping": [
      {
        "type": "Dimension",
        "name": "ResourceId"
      },
      {
        "type": "Dimension",
        "name": "ResourceType"
      },
      {
        "type": "Dimension",
        "name": "ResourceGroupName"
      },
      {
        "type": "Dimension",
        "name": "ResourceLocation"
      },
      {
        "type": "Dimension",
        "name": "SubscriptionName"
      },
      {
        "type": "Dimension",
        "name": "SubscriptionId"
      }
    ]
  }
}
EOF

curl \
  --silent \
  --request POST "${cost_management_url}" \
  --header "Authorization: Bearer ${access_token}" \
  --header "Content-Type: application/json" \
  --data-urlencode "${payload}" \
| jq .
