#!/bin/bash
input_json="${1:-data.json}"

jq -r '.properties.columns[].name' "${input_json?}" | paste -sd '\t' -

jq -r '.properties.rows[] | @tsv' "${input_json?}" \
| while read -r line; do
  echo -e "${line}"
done
