#!/bin/bash
INPUT_JSON="${1:-data.json}"

jq -r '.properties.columns[].name' "${INPUT_JSON?}" | paste -sd '\t' -

jq -r '.properties.rows[] | @tsv' "${INPUT_JSON?}" \
| while read -r LINE; do
  echo -e "$LINE"
done
