#!/bin/bash
THIS_SCRIPT_NAME=$0
THIS_SCRIPT_DIRECTORY=$(dirname $0)
PATH=${PATH}:${THIS_SCRIPT_DIRECTORY}

show_usage() {
  cat <<EOF
  
  Azure Costs

    Options:

      -h,  --help         Show this help
      -s,  --subscription Subscription ID
      -sd, --start-date   Start date
      -ed, --end-date     End date
     

    Examples:

      ${THIS_SCRIPT_NAME} \\
        --help

      ${THIS_SCRIPT_NAME} \\
        --subscription \${ARM_SUBSCRIPTION_ID} \\
        --start-date "2021-10-01" \\
        --end-date "2021-10-31"

EOF
}

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
  case $1 in
    -h | --help )
      show_usage
      exit 1
      ;;

    -s | --subscription )
      shift; SUBSCRIPTION_ID="${1}"
      ;;

    -sd | --start-date )
      shift; START_DATE="${1}"
      ;;
    
    -ed | --end-date )
      shift; END_DATE="${1}"
      ;;
  esac
  shift
done

if [[ "$1" == '--' ]]; then shift; fi

START_DATE="${START_DATE-2024-06-01}"
END_DATE="${END_DATE-2024-06-30}"

azure_account_list() {
  az account list \
    --query '[].{id: id,name: name}' \
    --output tsv \
  | grep "wasp"
}

rm costs-* &> /dev/null

while read -r SUBSCRIPTION_ID SUBSCRIPTION_DESCRIPTION; do
  echo "Subscription: ${SUBSCRIPTION_ID} ${SUBSCRIPTION_DESCRIPTION}"

  BASE_FILE_NAME="costs-${SUBSCRIPTION_ID?}_${START_DATE?}_${END_DATE?}"
  DATA_FILE_NAME="${BASE_FILE_NAME?}.json"
  ERROR_FILE_NAME="${BASE_FILE_NAME?}.log"

  azure-costs \
    --subscription "${SUBSCRIPTION_ID?}" \
    --start-date "${START_DATE?}" \
    --end-date "${END_DATE?}" > ${DATA_FILE_NAME?} 2> ${ERROR_FILE_NAME?}
done < <(azure_account_list)

## Convert json to tsv
while read -r JSON_FILE; do
  TSV_FILE_NAME="${JSON_FILE%.*}.tsv"
  echo "Converting: ${JSON_FILE} to ${TSV_FILE_NAME}"	
  json-to-tsv "${JSON_FILE}" > "${TSV_FILE_NAME}"
done < <(find -name 'costs-*.json' 2> /dev/null)

merge-tsv-files > costs-merged.tsv

echo "File costs-merged.tsv created."
